### PR TITLE
Perfect Number

### PR DESCRIPTION
**Pull request by sarveshsrv**
This algo checks whether a given no. is a perfect no. or not.
A positive  no. is said to be perfect if it is equal to the sum of its positive divisors.As: 6,28,496,8128, etc.

### CODE REVIEW

**Comment by gouravthakur39** [comment]
@sarveshsrv This repo contains c programs only.

**Comment by sarveshsrv** [comment]
> @sarveshsrv This repo contains c programs only.

The code is in C language.By mistake ,I used the extension .cpp instead of .c.

**Comment by gouravthakur39** [comment]
@sarveshsrv It's still CPP.

**Comment by sarveshsrv** [comment]
@gouravthakur39 .Sorry for that.Is it fine now??
Actually,I m a beginner on github.That's why, i am having some issues.

**Pull request merged**
