### PR TITLE
Polynomial linklist added

### PR DESCRIPTION
**Pull request by Leoperon**

### CODE REVIEW

**Comment by gouravthakur39** [comment]
Compilation error and please comment code :

main.c: In function ‘create’:
main.c:17:25: error: expected expression before ‘>’ token
     scanf("%d%d", & t - > coeff, & t - > exp);
                         ^
main.c:18:9: error: expected expression before ‘>’ token
     t - > next = NULL;
         ^
main.c:22:14: error: expected expression before ‘>’ token
       last - > next = t;
              ^
main.c: In function ‘Display’:
main.c:29:27: error: expected expression before ‘>’ token
     printf("%dx%d +", p - > coeff, p - > exp);
                           ^
main.c:30:13: error: expected expression before ‘>’ token
     p = p - > next;
             ^
main.c: In function ‘Eval’:
main.c:37:16: error: expected expression before ‘>’ token
     val += p - > coeff * pow(x, p - > exp);
                ^
main.c:38:13: error: expected expression before ‘>’ token
     p = p - > next;
             ^

**Comment by Leoperon** [comment]
#include<stdio.h>
#include<stdlib.h>
#include<math.h>
struct Node {
  int coeff;
  int exp;
  struct Node * next;
}* poly = NULL;
void create() {
  struct Node * t, * last = NULL;
  int num, i;
  printf("Enter number of terms");
  scanf("%d", & num);
  printf("Enter each term with coeff and exp\n");
  for (i = 0; i < num; i++) {
    t = (struct Node * ) malloc(sizeof(struct Node));
    scanf("%d%d", &t->coeff, &t->exp);
    t-> next = NULL;
    if (poly == NULL) {
      poly = last = t;
    } else {
      last -> next = t;
      last = t;
    }
  }
}
void Display(struct Node * p) {
  while (p) {
    printf("%dx%d +", p -> coeff, p -> exp);
    p = p -> next;
  }
  printf("\n");
}
long Eval(struct Node * p, int x) {
  long val = 0;
  while (p) {
    val += p -> coeff * pow(x, p -> exp);
    p = p -> next;
  }
  return val;
}
int main() {
  create();
  Display(poly);
  printf("%ld\n", Eval(poly, 1));
  return 0;
}

**Comment by Leoperon** [comment]
I have removed all the error

**Comment by Leoperon** [comment]
Any suggestions?

**Comment by gouravthakur39** [comment]
@Leoperon great. code compiled. please add some comments in your code so that other people( mostly beginners ) can understand. Also, format it for readability.

**Comment by Leoperon** [comment]
comment added :)

**Comment by gouravthakur39** [comment]
@Leoperon merged

**Pull request merged**
