### PR TITLE
A program on swapping two numbers without using a third variable name…

### PR DESCRIPTION
**Pull request by harry30225**
…d swapvaluewithoutusingthirdvariable111.c. 
swapping numbers using arithmetic(+,-) and assignment operators(=).

### CODE REVIEW

**Comment by gouravthakur39** [comment]
@harry30225 remove the binary file and rename the file to something general. I mean remove 111 at the end of the file name.

**Comment by harry30225** [comment]
@gouravthakur39 I have made the necessary changes suggested by you.kindly verify

**Comment by gouravthakur39** [comment]
@harry30225 You didn't remove the binary file. we don't need that. Also, please delete your old file which is : swapvaluewithoutusingthirdvariable111.c
Instructions for git in case you don't know:
1. `git status` - Tells what file changed
2. `git add filename` - files to be added for commit.
     You need to do `git add swappingwithoutthirdvariable.c`and then
3. `git commit -m "your commit message"`
Obviously, I am assuming things here.

**Comment by harry30225** [comment]
Done with it . Kindly verify

**Pull request merged**
