### PR TITLE
Added a Cprogram to check primality

### PR DESCRIPTION
**Pull request by Pulkit555**
I have added a Cprogram to check whether a no. is prime or not.
I have used math.h library and used sqrt predefined function and break condition to reduce the time complexity of the code to run.

### CODE REVIEW

**Comment by gouravthakur39** [comment]
@Pulkit555 

1. Users should know what to enter. 
2. Remove extra binary file

**Comment by Pulkit555** [comment]
I have made the changes according to you.
please check and verify me.

**Comment by gouravthakur39** [comment]
@Pulkit555 Result is always "Yes". Please fix it.

**Comment by gouravthakur39** [comment]
@Pulkit555 Also, the binary file is still there. please remove it. You need to exclude it while committing.
Instructions for git in case you don't know:
1. `git status` - Tells what file changed
2. `git add filename` - files to be added for commit.
     You need to do `git add swappingwithoutthirdvariable.c`and then
3. `git commit -m "your commit message"`
Obviously, I am assuming things here.

**Comment by gouravthakur39** [comment]
@Pulkit555 The binary file is still there.

**Comment by Pulkit555** [comment]
Thanks for merging my file .How could I contribute further?

**Pull request merged**
